### ISSUE TITLE
duplicate app window created

### ISSUE THREAD

**Issue by livelysalt** [crysfel/Bleextop#5]
When selecting an app from the desktop shortcuts or start menu, a new window is created, even if the app is already open. There seems to be a problem with:

[https://github.com/crysfel/Bleextop/blob/master/js/Bleext/desktop/WindowManager.js#L54]
`cfg.id = name.toLowerCase();`

`name` is undefined, so I've changed it to `cfg.title.toLowerCase();` and it works for me.

**Comment by livelysalt** [comment]
I've found that changing the code to reuse the currently-open app causes problems because it appears to reinitialize the app. I experience problems with events being fired multiple times (the number of times that I've re-opened the app as per the code change indicated above).

**Comment by livelysalt** [comment]
The problem seems to be that the app data remains in memory even when the app window is closed.

**Comment by crysfel** [comment]
mmmm... interesting, Thank you for reporting, I'll see what I can do

**Comment by crysfel** [comment]
Ok, I found the problem! 

Here are the lines of code that create the issue with the duplicated events

https://github.com/crysfel/Bleextop/blob/master/js/Bleext/desktop/Application.js#L82
https://github.com/crysfel/Bleextop/blob/master/js/Bleext/desktop/Application.js#L84

In order to fix it we need to define what behavior we want:

1.- When an user click in the start menu we can open the application ONLY ONE time, no matter how many times the user continue clicking the same shortcut we ALWAYS open ONE app.
2.- When an user click in the start menu we can open AGAIN the same app, no matter how many times the user clicks on the shortcut we will continue opening the same application again and again.

What do you think is the best behavior? or maybe both?

Regards

**Comment by livelysalt** [comment]
My expectation would be option 1 (only ONE instance of the app should be running), so I would want that to be the default behavior. However, I can imagine cases where multiple instances would be useful, so I would either make that an option in the app settings, and/or a menu option when the user right-clicks on the desktop shortcut or start menu item.

**Comment by crysfel** [comment]
Done! now we can configure in the "applications" module if we want a module to be "singleton", which means the window can be open only one time or many times, also I've added the code to remove the controller for each application when it's close and this also remove the selectors from the event bus.

Please let me know if these changes are working good for you.

Regards

**Comment by wilfoderek** [comment]
Shorcuts in thw new version are not appearing...please help....
